;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-slash
        c-indent-line-or-region
        comment-line
        electric-newline-and-maybe-indent
        ensime-company-complete-or-indent
        helm-M-x
        helm-show-kill-ring
        indent-for-tab-command
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        org-todo
        ))

(setq mc/cmds-to-run-once
      '(
        eval-print-last-sexp
        helm-mini
        jedi:goto-definition
        previous-buffer
        ))
