;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        c-electric-delete-forward
        c-electric-slash
        c-indent-line-or-region
        coffee-dedent-line-backspace
        comment-line
        electric-newline-and-maybe-indent
        ensime-company-complete-or-indent
        helm-M-x
        helm-show-kill-ring
        ignore
        indent-for-tab-command
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        org-todo
        org-yank
        sgml-slash
        typescript-insert-and-indent
        wrap-in-some
        ))

(setq mc/cmds-to-run-once
      '(
        dap-tooltip-mouse-motion
        eval-print-last-sexp
        fill-paragraph
        helm-mini
        help-for-help
        jedi:goto-definition
        lsp-signature-stop
        previous-buffer
        puppet-interpolate
        ))
